### ISSUE TITLE
Create change log page

### ISSUE THREAD

**Issue by ollimeier** [fontra/fontra-website#10]
Similar to what FontGoggles does, use the information stored in the fontra repository CHANGELOG.md to create a static HTML file. 

Please see:
https://github.com/googlefonts/fontra/issues/1748
https://github.com/justvanrossum/fontgoggles/tree/master/docsSource

Further notes:
- FontGoggles has a css file "markdown.css" which ~might be~ is of interest
- the python file and other code should live in this repo
- later: add requirements and make GitHub actions.
- add link to Fontra Help

**Comment by justvanrossum** [comment]
Note that the [FontGoggles](https://github.com/justvanrossum/fontgoggles/blob/master/docsSource/buildDocsSite.py) script does more than we need (process images, fonts).
