### ISSUE TITLE
[fontra] Users management flow diagram.

### ISSUE THREAD

**Issue by fabiocaccamo** [fontra/fontra-website#5]

**Comment by justvanrossum** [comment]
This isn't really the right repo for this topic. As a matter of fact, there is no repo for this topic yet...

**Comment by fabiocaccamo** [comment]
This issue has been created automatically from the project when I connected my task to this repo, feel free to close this, no problem.

**Comment by justvanrossum** [comment]
The task then shouldn't be connected to this repo.
